version: '3.7'

services:
  ngcf_model:
    image: ngcf
    build:
      context: .
      dockerfile: Dockerfile.cpu
      labels:
        - "tf=1.8.0"
        - "machine=cpu"
    command: python ./NGCF/NGCF.py --data_path ./Data/ --dataset gowalla --regs [1e-5] --embed_size 64 --layer_size [64,64,64] --lr 0.0001 --save_flag 1 --pretrain 0 --batch_size 1024 --epoch 400 --verbose 1 --node_dropout [0.1] --mess_dropout [0.1,0.1,0.1]
    volumes:
      - .:/model
